name: Deploy to Cloudflare Workers

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run CSS linting
        run: npm run test:css

      - name: Build
        run: npm run build

      - name: Run HTML validation
        run: npm run test:html

      - name: Run Lighthouse CI
        run: npm run test:lighthouse

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: ./dist
          retention-days: 1

  deploy:
    needs: test
    environment:
      name: cloudflare-workers
      url: https://www.hansonwong.au
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: ./dist

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
